### ISSUE TITLE
spatialAnalysis2 not work

### ISSUE THREAD

**Issue by qins** [kendomaniac/rCASC#2]
Thanks for the great rCASC.

It seems spatialAnalysis2 not exists?

![image](https://user-images.githubusercontent.com/3041080/91151130-deef0500-e6ef-11ea-9a2a-770e50d355ad.png)

**Comment by kendomaniac** [comment]
Thank for the message. 
We will upload again docker.io/repbioinfo/spatialanalysis2 on docker.io
Sorry for the inconvenience.

**Comment by qins** [comment]
(๑*◡*๑) thanks for your quick reply

**Comment by alessandriLuca** [comment]
Sorry for the late update. 
docker.io/repbioinfo/spatialanalysis2 is now online; let me know if everything will work fine. 
Thank you

**Comment by qins** [comment]
Now it's installed successfully, thanks ^_^

**Comment by alessandriLuca** [comment]
That's perfect! Enjoy ;)
